apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will42
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pierrickjay/InceptionOfThing
    targetRevision: main #branch
    path: p3/confs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true