apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app-v2
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
      version: v2
  template:
    metadata:
      labels:
        app: playground
        version: v2
    spec:
      containers:
      - name: playground-container
        image: wil42/playground:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service-v2
  namespace: dev
spec:
  selector:
    app: playground
    version: v2
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8080