Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine312"
  config.vm.define "axlamberS" do |webServer|
    webServer.vm.network "private_network", ip: "192.168.56.110"
    webServer.vm.synced_folder "./confs", "/vagrant", type: "virtualbox"
    webServer.vm.hostname = "axlamberS"
    webServer.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
      vb.name = "axlamberS"
    end
    webServer.vm.provision "shell", path: "./scripts/setup.sh"
  end
end
