Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true

	config.vm.provider "virtualbox" do |v|
		v.memory = 3024
		v.cpus = 3
	end

	config.vm.define :pjayS do |pjayS|
		pjayS.vm.hostname = 'thzeribi'
		pjayS.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--name", "thzeribi"]
		end

		pjayS.vm.provision "shell", privileged: true, path: "scripts/enable_X11.sh"
		pjayS.vm.provision "file", source: "scripts/", destination: "$HOME/"
		pjayS.vm.provision "file", source: "confs/", destination: "$HOME/"
	end
end